const appDisplayName = 'NetDrop';
const androidPackageName = 'com.qayham.netdrop';
const playStoreListingUrl =
    'https://play.google.com/store/apps/details?id=$androidPackageName';
const protocolVersion = '2.1';
const defaultPort = 53317;
const discoveryPort = 53316;
const portFallbackAttempts = 8;
const defaultDiscoveryTimeoutMs = 500;
const defaultMulticastGroup = '224.0.0.167';
const apiBasePath = '/api/netdrop/v2';
